/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Backtop: (typeof import('./../src/components/Backtop/src/Backtop.vue'))['default']
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider']
    LocaleDropdown: (typeof import('./../src/components/LocaleDropdown/src/LocaleDropdown.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
}
